package io.kyberorg.yalsee.exception;

import io.kyberorg.yalsee.ui.pages.err.err500.ServerErrorLoopPage;

/**
 * Exception, which not intended to be thrown, just {@link ServerErrorLoopPage} handles it.
 *
 * @since 2.7.4
 */
public class NeedForLoopException extends YalseeException {
}
